condense_wildcard_suffixes = true
edition = "2021"
format_code_in_doc_comments = true
empty_item_single_line = false
fn_single_line = false
force_multiline_blocks = true
inline_attribute_width = 50
imports_layout = "HorizontalVertical"
imports_granularity = "Crate"
newline_style = "Unix"
group_imports = "StdExternalCrate"
unstable_features = true
struct_field_align_threshold = 20     # structの20文字以内のフィールドを縦に揃える
enum_discrim_align_threshold = 20     # 列挙型で20文字以内の要素を縦に揃える
use_field_init_shorthand = true       # フィールド初期化のとき、可能であれば省略形を使用する
